set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -g mouse on
set -g allow-rename off
set -g renumber-windows off
set -g history-limit 100000
set -g status-position top
set -g mode-keys vi
set -g base-index 1
set -g prefix M-a
set -g repeat-time 500
set -g renumber-windows off
set -g escape-time 10
#set -g focus-events on

unbind C-b
bind r source-file ~/.tmux.conf \; display-message 'reload ~/.tmux.conf'
bind c new-window -c "#{pane_current_path}"
bind C new-window \; new-window \; new-window \; new-window \; new-window \; new-window \; new-window \; new-window \; new-window
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind v copy-mode \; send -X begin-selection
bind h copy-mode \; send -X cursor-left
bind j copy-mode \; send -X cursor-down
bind k copy-mode \; send -X cursor-up
bind l copy-mode \; send -X cursor-right
bind p paste
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel
unbind L
bind H swap-pane -d -t '{left-of}'
bind J swap-pane -d -t '{down-of}'
bind K swap-pane -d -t '{up-of}'
bind L swap-pane -d -t '{right-of}'

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10
bind -n End send-key C-e
bind -n Home send-key C-a
bind s setw synchronize-panes \; display-message "synchronize-panes: #{?pane_synchronized,on,off}"


set -g status-bg "colour236"
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g status-right-length "100"
set -g window-status-separator ""
set -g status-left ""
set -g status-right "#[fg=colour253] %Y/%m/%d %H:%M"
set -g window-status-format "#[fg=colour244] #I.#W "
set -g window-status-current-format "#[fg=colour253,bg=colour239] #I.#W "
set -g @resurrect-processes 'false'
set -g @resurrect-strategy-vim ''

#set -g @plugin 'seebi/tmux-colors-solarized'
#set -g @colors-solarized 'base16'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

run '~/.tmux/plugins/tpm/tpm'
